[package]
name = "squashfs"
version = "0.1.0"
authors = ["Matthew Schauer <matthew.schauer@e10x.net>"]
edition = "2018"

[build-dependencies]
bindgen = "0.53.1"

[dependencies]
libc = "0.2"
mmap = "0.1"
num-traits = "0.2"
num-derive = "0.3"
owning_ref = "0.4"
thiserror = "1.0"
walkdir = "2.3"
